project:
  type: website

website:
  title: "DaVinci"
  navbar:
    pinned: true
    collapse: true
    search: true
    left:
      - quarto/getting_started.qmd
      - quarto/modules.qmd
      - about.qmd
    right:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/Boehringer-Ingelheim/davinci
          - text: Report a Bug
            url: https://github.com/Boehringer-Ingelheim/davinci/issues
  page-footer:
    center:
      - text: "This website as well as the DaVinci packages are licensed under the Apache License, Version 2.0." # nolint
    right:
      - aria-label: GitHub
        href: https://github.com/Boehringer-Ingelheim/davinci
        icon: github

format:
  html:
    theme: [cosmo, quarto/general.scss]
    css: quarto/style.scss
    toc: false
    page-layout: full
    anchor-sections: true




