---
title: "DaVinCI Modules"
execute:
  echo: false
format:
  html:
    toc: true
lightbox:
  match: auto
---


## General packages:

### Data loader by [{dv.loader}](https://boehringer-ingelheim.github.io/dv.loader/){target="_blank"}
The data loader supports the loading of data from a file system.

### Global filter by [{dv.filter}](https://boehringer-ingelheim.github.io/dv.filter/){target="_blank"}
The global filter provides variable filters that can be activated and deactivated at run time by the user. It is presented at the sidebar of each DaVinCI App, thus it is incorporated into the module manager. When effective, only subjects who meet the filter criteria are displayed throughout all modules.

### Module Manager by [{dv.manager}](https://boehringer-ingelheim.github.io/dv.manager/){target="_blank"}
The module manager is the heart of each DaVinCI app and provides all requested outputs (also called modules), as well as meta information around the data. It takes care of jumping between modules, switching between data from different trials, and displaying a custom start-up message.



## Modules:
### Listings by [{dv.listings}](https://boehringer-ingelheim.github.io/dv.listings/){target="_blank"} 
  
::: columns
::: {.column width="40%"}

```{r}
#| warning: false
#| fig-cap: Listings module
#| lightbox:
#|   group: listings
#|   description: This is the Listings module
source("carousel/carousel.R")
carousel("gallery-carousel", 5000,
       yaml.load_file("carousel/carousel.yml"))
```

:::
::: {.column width="60%"}
The listings module displays arbitrary datasets as listings. Users can select the dataset to be shown, and specify which columns of the dataset should be displayed as well as their order. The displayed columns can be sorted and filtered. Moreover, the table can be filtered to show only entries containing a keyword entered by the user. The module is not limited to usage of one data source, most notably, it can handle data from ADaM or SDTM.
:::
:::

